name: sa_orange_lego
description: "orange template under simple architecture framework"
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_orange_lego

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  orange:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  sa_data_class_lego:
  orange_lego: #@add
  widget_binding_lego:
  usage_note_lego:

flutter:
  assets:
    - assets/lego/sa_orange_lego/
  uses-material-design: true

topics:
  - lego